// SPDX-FileCopyrightText: Copyright 2026 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// HLE call bridge for the x86-64 interpreter.
//
// When shadPS4 resolves an HLE library call (e.g. libkernel's
// sceKernelMmap), the linker patches the call site to jump to a stub
// generated by AeroLib::GetStub(). On x86 hosts the stub is x86-64
// code that loads the index into rdi and jumps to CommonStub. On
// ARM64 hosts the stub is ARM64 code — but the interpreter doesn't
// know how to execute ARM64 code, so we need to detect stub addresses
// and call CommonStub directly via a host function pointer.
//
// This file exposes:
//   - IsAerolibStubAddress(rip) — true if rip points into the stub arena.
//   - DispatchAerolibStub(rip, &state) — invokes the CommonStub host
//     function and updates the guest's RAX/RIP to reflect the HLE
//     return.

#include "core/cpu/interpreter/x64_interpreter_backend.h"

#include <cstdint>
#include <cstring>

#include "common/assert.h"
#include "common/logging/log.h"
#include "core/aerolib/stubs.h"
#include "core/cpu/x64_cpu_state.h"

namespace Core::Cpu {

// ─────────────────────────────────────────────────────────────────────────
//  Internals — we re-mirror the static data from src/core/aerolib/stubs.cpp
//  via a small accessor that exposes the arena range. To avoid touching
//  the existing stubs.cpp API we instead use a brute-force detection:
//  we mmap an arena at a fixed range (the existing code uses an
//  anonymous mmap which is non-deterministic). For now we expose the
//  detection via the stubs.cpp GetStubArena helper — added below.
// ─────────────────────────────────────────────────────────────────────────

namespace {

// Forward decl of the host CommonStub that lives in stubs.cpp. We
// re-declare it here so this TU can call it without including the
// private stubs.cpp internals.
extern "C" u64 PS4_SYSV_ABI AeroLibCommonStub(u64 index);

} // namespace

// ─────────────────────────────────────────────────────────────────────────
//  Public API
// ─────────────────────────────────────────────────────────────────────────

// Stub address book — populated by the loader when it asks AeroLib for
// stubs. We remember the range so the interpreter can detect calls into
// the stub arena and divert them to CommonStub.
namespace {
struct StubArena {
    u64 base = 0;
    u64 size = 0;
    bool operator==(const StubArena&) const = default;
    explicit operator bool() const { return base != 0 && size != 0; }
};

StubArena g_arena;
} // namespace

// Called by the interpreter before dispatching a CALL/JMP to a target
// RIP. If the target is inside the stub arena we run the HLE handler
// directly and update the guest state.
bool IsAerolibStubAddress(u64 rip) {
    return g_arena && rip >= g_arena.base && rip < g_arena.base + g_arena.size;
}

// The loader calls this once at startup to tell us where the stub
// arena lives. We expose it via a C-linkage function so the stubs.cpp
// side can register without needing to include this header.
extern "C" void Core_Cpu_RegisterAerolibStubArena(u64 base, u64 size) {
    g_arena = {base, size};
    LOG_INFO(Core_Cpu, "Registered AeroLib stub arena at 0x{:016x} size 0x{:x}", base, size);
}

// Run the HLE handler for a stub address. Returns the new RIP (i.e. the
// guest's return address). The guest's RAX is updated to the HLE return
// value.
//
// We assume the stub layout used by AeroLib on ARM64:
//   movz w0, #(index & 0xFFFF)
//   movk w0, #((index >> 16) & 0xFFFF), lsl #16
//   movz x16, #(target & 0xFFFF)
//   movk x16, #(target >> 16) , lsl #16
//   movk x16, #(target >> 32) , lsl #32
//   movk x16, #(target >> 48) , lsl #48
//   br x16
//
// To avoid re-decoding this, we decode just enough to recover the index
// (the first two instructions: movz w0, #imm16 + movk w0, #imm16, lsl #16).
// We then call CommonStub(index) directly.
//
// The CommonStub implementation lives in src/core/aerolib/stubs.cpp. We
// call it via a host function pointer (not via the stub code itself,
// because we can't execute ARM64 code in the interpreter).
bool DispatchAerolibStub(u64 rip, X64CpuState* state) {
    if (!IsAerolibStubAddress(rip)) return false;

    // Decode the index from the first two ARM64 instructions.
    const u32* code = reinterpret_cast<const u32*>(rip);
    const u32 i0 = code[0];
    const u32 i1 = code[1];
    // movz w0, #imm16 (encoding 0x52800000 | (imm16 << 5) | 0)
    // movk w0, #imm16, lsl #16 (encoding 0x72A00000 | (imm16 << 5))
    if ((i0 & 0xFFE0001F) != 0x52800000u || (i1 & 0xFFE0001F) != 0x72A00000u) {
        LOG_ERROR(Core_Cpu, "DispatchAerolibStub: stub at 0x{:016x} doesn't match expected layout",
                  rip);
        return false;
    }
    const u64 low  = (i0 >> 5) & 0xFFFFu;
    const u64 high = (i1 >> 5) & 0xFFFFu;
    const u64 index = low | (high << 16);

    LOG_TRACE(Core_Cpu, "Dispatching HLE stub at 0x{:016x} (index={})", rip, index);
    const u64 result = AeroLibCommonStub(index);

    // Update the guest's RAX with the HLE return value (the PS4 ABI
    // returns integers in RAX, and stubs always return 0 for
    // unimplemented functions, so this is safe).
    state->gpr[GPR_RAX] = result;

    // Pop the return address off the guest stack and set RIP to it.
    // This matches a "ret" instruction.
    state->rip = ReadMemory(state->gpr[GPR_RSP], 8, false);
    state->gpr[GPR_RSP] += 8;
    return true;
}

} // namespace Core::Cpu
